name: pypsa_dc_5
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - gurobi
dependencies:
  # Python Core & Tools
  - python=3.10
  - pip
  - setuptools
  - wheel
  - xz
  - zlib
  - zeromq
  - pyzmq
  - jupyter_client
  - jupyter_core
  - ipykernel
  - ipython
  - tornado
  - traitlets
  - decorator
  - jedi
  - parso
  - pexpect
  - ptyprocess
  - prompt-toolkit
  - wcwidth
  - tk
  - openssl
  - libffi
  - ca-certificates
  
  # Wissenschaftliche Bibliotheken & Pyomo
  - numpy
  - scipy
  - pandas
  - xarray
  - numpydoc
  - bottleneck
  - numexpr
  - pyomo
  - highs
  - gurobi=12.0
  - ipopt
  - mumps-seq
  - linopy
  
  # Geo- und Plotting-Bibliotheken
  - matplotlib-base
  - kiwisolver
  - pillow
  - pyyaml
  - cython
  - cartopy
  - cairo
  - fiona
  - gdal=3.6
  - geographiclib
  - geopandas=1.1
  - geos
  - geotiff
  - proj=9.3
  - rasterio=1.4
  - rtree
  - shapely
  - xyzservices
  - mercantile
  - contextily
  - folium
  - branca
  - mapclassify
  
  # IO und Datenformate
  - hdf5
  - netcdf4
  - libnetcdf
  - tiledb
  - lxml
  - openjpeg
  - libpng
  - libtiff
  - jpeg
  - blosc
  - lerc
  - zstd
  - minizip
  - tiledb
  
  # System- und Utility-Pakete
  - libxml2
  - libcurl
  - libssh2
  - cryptography
  - ncurses
  - libiconv
  - libsodium
  - lz4-c
  - pcre2
  - text-unidecode
  - attrs
  - markupsafe
  - python-dateutil
  - pytz
  - tzdata
  - requests
  - urllib3
  - idna
  - certifi
  - six
  - packaging
  
  # Linter, Formatierer & Spyder (Optional, aber beibehalten)
  - spyder
  - spyder-kernels
  - pylint
  - flake8
  - black
  - isort
  - autopep8
  - pycodestyle
  - pyflakes
  - rope
  - rich
  - docstring-to-markdown
  - keyring
  - whatthepatch
  
  # GUI-Komponenten
  - qt-main=5.15
  - pyqt=5.15
  - qt-webengine
  - pyqtwebengine
  - qtawesome
  - qdarkstyle
  - qtconsole
  - qtpy
  - sip
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cbc==0.0.7
      - certifi==2025.8.3
      - cfgv==3.4.0
      - cftime==1.6.4.post1
      - click==8.2.1
      - commonmark==0.9.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepdiff==8.6.1
      - distlib==0.4.0
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - gast==0.6.0
      - geojson==3.2.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - highspy==1.11.0
      - id==1.5.0
      - identify==2.6.13
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - jeepney==0.9.0
      - keras==3.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - lxml==6.0.1
      - markdown==3.8.2
      - matplotlib==3.10.3
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - narwhals==1.48.0
      - netcdf4==1.7.2
      - nh3==0.3.0
      - nodeenv==1.9.1
      - numexpr==2.11.0
      - numpy==2.1.3
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - orderly-set==5.5.0
      - packaging==25.0
      - pandapower==3.1.2
      - pandas==2.3.1
      - pep517==0.13.1
      - pkginfo==1.12.1.2
      - plotly==6.2.0
      - polars==1.31.0
      - pre-commit==4.3.0
      - protobuf==5.29.5
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyproject-hooks==1.2.0
      - pypsa==0.0.post1.dev2970+g512389175.d20251209
      - readme-renderer==44.0
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rsa==4.9.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - shapely==2.0.7
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.19.0
      - tensorflow-addons==0.22.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - twine==6.1.0
      - typeguard==2.13.3
      - validators==0.35.0
      - virtualenv==20.34.0
      - werkzeug==3.1.3
      - xlsxwriter==3.2.9
      - zipp==3.23.0
prefix: C:\Users\E370_\anaconda3\envs\pypsa_dc_5


