name: pypsa_dc_5
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - gurobi
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - affine=2.4.0=pyhd8ed1ab_1
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py310hdb0e946_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - ampl-asl=1.0.0=he0c23c2_2
  - aom=3.6.0=hd77b12b_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - astroid=3.3.11=py310h5588dad_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - asyncssh=2.21.0=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=24.3.0=py310haa95532_0
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - bcrypt=4.3.0=py310h034784e_2
  - beautifulsoup4=4.13.5=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.1.0=pyha5154f8_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=h4190f5b_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.5.0=py310hb0944cc_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli-python=1.0.9=py310h5da7b33_9
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.16.0=hd694305_1014
  - cartopy=0.25.0=py310hed136d8_0
  - cffi=1.17.1=py310h827c3e9_1
  - cfitsio=3.470=h0af3d06_7
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - contextily=1.6.2=pyhd8ed1ab_1
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.10.18=py310hd8ed1ab_0
  - cryptography=45.0.7=py310he482ccc_1
  - dask-core=2025.7.0=pyhe01879c_1
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py310h699e580_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.0=pyhd8ed1ab_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - fiona=1.9.1=py310h4a685fe_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=hb33846d_3
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - freexl=2.0.0=h8276f4a_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.7.0=py310had1666a_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - fzf=0.65.2=hb13f615_0
  - gdal=3.6.2=py310he1c868a_9
  - geographiclib=2.1=pyhd8ed1ab_0
  - geopandas=1.1.1=pyhd8ed1ab_0
  - geopandas-base=1.1.1=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_2
  - geos=3.10.6=he74ecf9_0
  - geotiff=1.7.0=h4545760_3
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.78.4=h12be248_0
  - glib-tools=2.78.4=h12be248_0
  - glpk=5.0=h8ffe710_0
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - gurobi=12.0.3=py310_0
  - harfbuzz=6.0.0=he256f1b_0
  - hdf4=4.2.13=h0e5069d_1005
  - hdf5=1.12.1=h51c971a_3
  - highs=1.11.0=h79cd779_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=70.1=h0e60522_0
  - idna=3.7=py310haa95532_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipopt=3.14.17=h812a801_2
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - isort=6.0.1=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.1.3=py310hc226416_0
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - kealib=1.5.0=hde4a422_1
  - keyring=25.6.0=pyh7428d3b_0
  - kiwisolver=1.4.8=py310h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h5da7b33_0
  - libarchive=3.7.7=h9243413_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libavif=1.1.1=h827c3e9_0
  - libblas=3.9.0=32_h641d27c_mkl
  - libboost=1.82.0=h3399ecb_2
  - libcblas=3.9.0=32_h5e41251_mkl
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.14.1=h2300eb9_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=he0cae08_9
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.78.4=h16e383f_0
  - libhwloc=2.11.2=default_h88281d1_1002
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libkml=1.3.0=h63940dd_7
  - liblapack=3.9.0=32_h1aa476e_mkl
  - libnetcdf=4.8.1=h6685c40_4
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=2.1.0=h518811d_0
  - libspatialite=5.1.0=h6715bb4_2
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=h44ae7cf_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.3.2=hcfcfb64_1
  - libwebp-base=1.3.2=h3d04722_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxml2=2.13.8=h866ff63_0
  - libzip=1.8.0=h519de47_1
  - libzlib=1.2.13=h2466b09_6
  - linopy=0.5.5=pyhd8ed1ab_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h827c3e9_0
  - matplotlib-base=3.10.0=py310he19b0ae_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mercantile=1.2.1=pyhd8ed1ab_1
  - minizip=4.0.3=hb68bac4_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h66d3029_15
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - multidict=6.6.3=py310hdb0e946_0
  - mumps-seq=5.7.3=hbaa6519_10
  - munch=4.0.0=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpydoc=1.9.0=pyhe01879c_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - pandoc=3.7.0.2=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.42=h0ff8eda_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py310hb5480e2_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=py310haa95532_0
  - polars-default=1.32.3=py39he906d20_0
  - poppler=24.09.0=h4f47ea2_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - proj=9.3.1=ha107b6e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py310h38315fa_0
  - psutil=7.0.0=py310h29418f3_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=3.3.8=pyhe01879c_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py310h635b8f1_3
  - pyogrio=0.10.0=py310he5c4563_0
  - pyomo=6.9.2=py310h9e98ed7_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h1fd54f2_5
  - pyqt5-sip=12.12.2=py310h00ffb61_5
  - pyqtwebengine=5.15.9=py310he49db7d_5
  - pyshp=2.3.1=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.10.18=hd8ed1ab_0
  - python-gssapi=1.8.2=py310ha50d041_2
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.2=pyhff2d567_0
  - python-lsp-server-base=1.12.2=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py310h282bd7d_1
  - pywin32-ctypes=0.2.3=py310h5588dad_2
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=27.0.2=py310h535538e_2
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=hc790b64_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.8=h720456b_6
  - qt-webengine=5.15.8=h5b1ea0b_0
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.6.1=pyhd8ed1ab_2
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - rasterio=1.4.3=py310he5c4563_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=py310haa95532_0
  - rich=14.1.0=pyhe01879c_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.27.1=py310h034784e_1
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.12.11=h429b229_0
  - scienceplots=2.1.1=pyhd8ed1ab_1
  - scikit-learn=1.7.1=py310h21054b0_0
  - setuptools=78.1.1=py310haa95532_0
  - sip=6.7.12=py310h00ffb61_0
  - six=1.17.0=py310haa95532_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.0.8=hd8ed1ab_0
  - spyder-base=6.0.8=py310h5588dad_0
  - spyder-kernels=3.0.5=win_pyh7428d3b_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.6=pyhb6d5dde_0
  - tbb=2021.13.0=h62715c5_1
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tiledb=2.3.3=hd8964de_3
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h5e9d12e_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tomlkit=0.13.3=pyha770c72_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py310h29418f3_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.11.0=py310h699e580_1
  - unicodedata2=15.1.0=py310h827c3e9_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py310h5588dad_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wrapt=1.17.3=py310h29418f3_1
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=he0c23c2_2
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.20.1=py310h38315fa_0
  - zeromq=4.3.5=he0c23c2_3
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cbc==0.0.7
      - certifi==2025.8.3
      - cfgv==3.4.0
      - cftime==1.6.4.post1
      - click==8.2.1
      - commonmark==0.9.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepdiff==8.6.1
      - distlib==0.4.0
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - gast==0.6.0
      - geojson==3.2.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - highspy==1.11.0
      - id==1.5.0
      - identify==2.6.13
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - jeepney==0.9.0
      - keras==3.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - lxml==6.0.1
      - markdown==3.8.2
      - matplotlib==3.10.3
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - narwhals==1.48.0
      - netcdf4==1.7.2
      - nh3==0.3.0
      - nodeenv==1.9.1
      - numexpr==2.11.0
      - numpy==2.1.3
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - orderly-set==5.5.0
      - packaging==25.0
      - pandapower==3.1.2
      - pandas==2.3.1
      - pep517==0.13.1
      - pkginfo==1.12.1.2
      - plotly==6.2.0
      - polars==1.31.0
      - pre-commit==4.3.0
      - protobuf==5.29.5
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyproject-hooks==1.2.0
      - pypsa==0.0.post1.dev2970+g512389175.d20251209
      - readme-renderer==44.0
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rsa==4.9.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - shapely==2.0.7
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.19.0
      - tensorflow-addons==0.22.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - twine==6.1.0
      - typeguard==2.13.3
      - validators==0.35.0
      - virtualenv==20.34.0
      - werkzeug==3.1.3
      - xlsxwriter==3.2.9
      - zipp==3.23.0
prefix: C:\Users\E370_\anaconda3\envs\pypsa_dc_5


