name: pypsa_hybrid
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  # Python Core & Tools
  - python=3.10
  - pip
  - setuptools
  - wheel
  - xz
  - zlib
  - zeromq
  - pyzmq
  - jupyter_client
  - jupyter_core
  - ipykernel
  - ipython
  - tornado
  - traitlets
  - decorator
  - jedi
  - parso
  - pexpect
  - ptyprocess
  - prompt-toolkit
  - wcwidth
  - tk
  - openssl
  - libffi
  - ca-certificates
  
  # Wissenschaftliche Bibliotheken & Pyomo
  - numpy
  - scipy
  - pandas
  - xarray
  - numpydoc
  - bottleneck
  - numexpr
  - pyomo
  - highs
  - ipopt
  - mumps-seq
  - linopy
  
  # Geo- und Plotting-Bibliotheken
  - matplotlib-base
  - kiwisolver
  - pillow
  - pyyaml
  - cython
  - cartopy
  - cairo
  - fiona
  - gdal=3.6
  - geographiclib
  - geopandas=1.1
  - geos
  - geotiff
  - proj=9.3
  - rasterio=1.4
  - rtree
  - shapely
  - xyzservices
  - mercantile
  - contextily
  - folium
  - branca
  - mapclassify
  
  # IO und Datenformate
  - hdf5
  - netcdf4
  - libnetcdf
  - tiledb
  - lxml
  - openjpeg
  - libpng
  - libtiff
  - jpeg
  - blosc
  - lerc
  - zstd
  - minizip
  - tiledb
  
  # System- und Utility-Pakete
  - libxml2
  - libcurl
  - libssh2
  - cryptography
  - libsodium
  - lz4-c
  - pcre2
  - text-unidecode
  - attrs
  - markupsafe
  - python-dateutil
  - pytz
  - tzdata
  - requests
  - urllib3
  - idna
  - certifi
  - six
  - packaging
  
  # Linter, Formatierer & Spyder (Optional, aber beibehalten)
  
  # GUI-Komponenten










