name: pypsa_core_3
channels:
  - conda-forge
  - defaults
dependencies:
  # Kern-Python
  - python=3.10
  
  # Kernwissenschaftliche Bibliotheken (NumPy/Pandas/SciPy)
  - numpy
  - pandas
  - scipy
  
  # Pyomo und Solver (HiGHS für Stabilität)
  - pyomo
  - highs
  - ipopt
  
  # PyPSA-Kernabhängigkeiten (z.B. xarray, netcdf4)
  - xarray
  - netcdf4
  - lxml
  
  # Graphik (Nur Matplotlib, kein Qt/Spyder)
  - matplotlib
  
  # Pip-Schnittstelle
  - pip
